version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: marinachernykh/hiking:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  gateway:
    image: marinachernykh/hiking-gateway:latest
    ports:
      - 8000:80
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web


volumes:
  db_value:
  static_value:
  media_value:
