# Generated by Django 4.2.6 on 2023-10-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_alter_trail_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionphoto',
            options={'verbose_name': 'Фото региона', 'verbose_name_plural': 'Фото региона'},
        ),
        migrations.AlterModelOptions(
            name='trailphoto',
            options={'verbose_name': 'Фото маршрута', 'verbose_name_plural': 'Фото маршрута'},
        ),
        migrations.AlterField(
            model_name='trail',
            name='time',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Время на маршрут в часах'),
            preserve_default=False,
        ),
    ]
