# Generated by Django 4.2.6 on 2023-11-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_region_mobile_image_trail_mobile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('id',), 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterField(
            model_name='trail',
            name='route_image',
            field=models.URLField(blank=True, verbose_name='Карта маршрута'),
        ),
    ]
