# Generated by Django 4.2.6 on 2023-11-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('author', 'ranking', 'text'), name='Unique comment constraint'),
        ),
    ]
