# Generated by Django 4.2.6 on 2023-11-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_comment_unique_comment_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='Unique comment constraint',
        ),
    ]
