# Generated by Django 4.2.6 on 2023-10-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_alter_trail_distance_alter_trail_elevation_gain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус публикации'),
        ),
    ]
