# Generated by Django 4.2.6 on 2023-10-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0006_alter_comment_created'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('text__exact', ''), _negated=True), ('ranking__isnull', False), _connector='OR'), name='not_both_empty'),
        ),
    ]
