# Generated by Django 4.2.6 on 2023-10-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_comment_not_both_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='card_image',
            field=models.ImageField(blank=True, upload_to='trails/cards', verbose_name='Фото для карточки маршрута'),
        ),
    ]
