name: hiking_workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          USER: postgres_user
          PASSWORD: postgres_password
          NAME: postgres_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r hiking/requirements.txt

    - name: Test with flake8 and django tests
      env:
          USER: postgres_user
          PASSWORD: postgres_password
          NAME: postgres_db
          HOST: 127.0.0.1
          PORT: 5432
      run: |
        cd hiking/
        python flake8
        python manage.py test
